Concert
29td/concert-website pull request #1
Opened 2022-06-29 10:02 UTC by 29td

Creating my first capstone project.

2022-06-30 14:06 UTC, vechicin requested changes
# Hi @29td ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️

- [ ] Requesting your project to be seen at a specific zoom percentage is not acceptable because your users won't know they need to do this. You need to make sure your content works at 100% zoom, please fix it.

- [ ] Please change your PR title/description to something more descriptive

- [ ] You need to submit a video presentation for this project, please do so.
 
<img width="949" alt="Screen Shot 2022-06-30 at 8 14 47" src="https://user-images.githubusercontent.com/82426682/176686339-3e659d47-3e8b-4e87-9c61-5413911a9e24.png">

- [ ] You need to match the template design, please fulfill all the requirements below.

<img width="645" alt="Screen Shot 2022-06-30 at 9 00 49" src="https://user-images.githubusercontent.com/82426682/176696891-d886ddab-844b-47ec-a2ef-ed303cf5f29c.png">

- [ ] The way your HTML code is structured is not correct, please fulfill all the requirements below.

<img width="991" alt="Screen Shot 2022-06-30 at 9 02 11" src="https://user-images.githubusercontent.com/82426682/176697181-e117b7d8-4711-43f0-a782-887e711b4871.png">


_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 14:06 UTC, vechicin commented on README.md
> +- It is such a great honour to be sharing my work with everyone. I know some may learn something from my work some may help me learn new things too.
<img width="1041" alt="Screen Shot 2022-06-30 at 8 15 48" src="https://user-images.githubusercontent.com/82426682/176686590-be4e60bd-2980-42d5-be8d-b84c0792a73d.png">

Please fix it.

2022-06-30 14:06 UTC, vechicin commented on README.md
> +https://29td.github.io/My-First-Portfolio/
You submitted a demo to your portfolio, please fix it.

<img width="517" alt="Screen Shot 2022-06-30 at 8 17 14" src="https://user-images.githubusercontent.com/82426682/176686860-c3d0eced-5dc6-49b0-9686-764391bf7b2a.png">

2022-06-30 14:06 UTC, vechicin commented on about.html
> +            </li>
There should be a link that allows users to navigate back to the home page, please add it.

<img width="732" alt="Screen Shot 2022-06-30 at 8 20 40" src="https://user-images.githubusercontent.com/82426682/176687663-59ce41e3-8ccf-40af-a7df-1d109759cc2d.png">

2022-06-30 14:06 UTC, vechicin commented on about.html
> +    </div>
This content should be aligned further right to match the template design, please fix it.

Additionally, you need to use the font provided in the template design, please fix that as well.

2022-06-30 14:06 UTC, vechicin commented on about.html
> +        <a href="#link"><img src="./assets/Images/logo.png" alt="img"/></a>
Please fix the logo's image size, it looks very squished right now.

2022-06-30 14:06 UTC, vechicin commented on index.html
> +    <img src="./assets/Images/logo.png" alt="img"/><span>@copy right reserver summer festival 2022</span>
This text is not visible, please fix its color.

You should fix the image size as well.

<img width="215" alt="Screen Shot 2022-06-30 at 8 38 19" src="https://user-images.githubusercontent.com/82426682/176691565-1c5899dc-45aa-4364-af43-c1034d41d921.png">

Please fix that.

<img width="298" alt="Screen Shot 2022-06-30 at 8 38 38" src="https://user-images.githubusercontent.com/82426682/176691642-d3f414e0-4749-4ba9-b97e-d07e33871253.png">

Please add a footer to your `About` page and make sure the background colors are correct.

2022-06-30 14:06 UTC, vechicin commented on index.html
> +    </div>
<img width="1055" alt="Screen Shot 2022-06-30 at 8 44 04" src="https://user-images.githubusercontent.com/82426682/176692882-e1c27236-7069-4994-b965-c3bb868d504c.png">

Please make sure this section fulfills all of these requirements.

2022-06-30 14:06 UTC, vechicin commented on index.html
> +    </div>
This content is not centered, please fix it.

2022-06-30 14:06 UTC, vechicin commented on index.html
> +</div>
The content is not centered, please fix it.

Additionally, in the mobile version, the margins are not quite right and some of the content is overflowing into the container below, please fix it.

<img width="1041" alt="Screen Shot 2022-06-30 at 8 51 51" src="https://user-images.githubusercontent.com/82426682/176694684-873e6306-9b6e-4e71-b8bf-8643b15cd8e5.png">

Please fix this issue for the mobile version as well.

<img width="1018" alt="Screen Shot 2022-06-30 at 8 53 03" src="https://user-images.githubusercontent.com/82426682/176695025-50e594f7-6f17-497a-b502-301e6ac3f9c5.png">

Fix this issue as well.

2022-06-30 14:06 UTC, vechicin commented on index.html
> +</div>
The content is not centered, please fix it.

<img width="1044" alt="Screen Shot 2022-06-30 at 8 48 51" src="https://user-images.githubusercontent.com/82426682/176693915-9eff2c08-5fe7-442e-8758-c66ae3b3b18f.png">

Make sure this section fulfills all of these requirements.

2022-06-30 14:06 UTC, vechicin commented on about.html
> +</section>
<img width="1055" alt="Screen Shot 2022-06-30 at 8 58 12" src="https://user-images.githubusercontent.com/82426682/176696246-c1d429c7-9eaa-4d53-98a7-b4f5a8c64156.png">

Your `About` page design is very disorganized. Please make sure you center all of your content properly and make sure the text over the images is clearly visible.

2022-06-30 14:06 UTC, vechicin commented on script.js
> +}];
<img width="971" alt="Screen Shot 2022-06-30 at 9 04 23" src="https://user-images.githubusercontent.com/82426682/176697650-9512784d-4526-4b5a-af32-39a5ea7e7c46.png">

Please make sure your speaker objects hold all of the information above.

2022-07-01 20:29 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @29td     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 05:33 UTC, merged